import { createHmac, timingSafeEqual } from "node:crypto";

const RAZORPAY_API_URL = "https://api.razorpay.com/v1";

interface RazorpayConfig {
  keyId: string;
  keySecret: string;
}

/** Returns the configured Razorpay credentials or null when not set up. */
export function razorpayConfig(): RazorpayConfig | null {
  const keyId = process.env.RAZORPAY_KEY_ID;
  const keySecret = process.env.RAZORPAY_KEY_SECRET;
  if (!keyId || !keySecret) return null;
  return { keyId, keySecret };
}

/** Whether Razorpay payments are available for this deployment. */
export function razorpayConfigured(): boolean {
  return razorpayConfig() !== null;
}

async function razorpayFetch<T>(
  method: "GET" | "POST",
  path: string,
  body?: unknown,
): Promise<T> {
  const config = razorpayConfig();
  if (!config) {
    const error = new Error("Payments are not configured on this server") as Error & {
      status?: number;
    };
    error.status = 503;
    throw error;
  }

  const auth = Buffer.from(`${config.keyId}:${config.keySecret}`).toString(
    "base64",
  );

  const res = await fetch(`${RAZORPAY_API_URL}${path}`, {
    method,
    headers: {
      Authorization: `Basic ${auth}`,
      "Content-Type": "application/json",
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    const error = new Error(
      `Razorpay request failed (${res.status}): ${text.slice(0, 500)}`,
    ) as Error & { status?: number };
    error.status = res.status;
    throw error;
  }

  return (await res.json()) as T;
}

export interface RazorpayOrder {
  id: string;
  amount: number;
  amount_paid: number;
  currency: string;
  receipt: string | null;
  status: string;
  entity: string;
}

/**
 * Creates a Razorpay order server-side. `amountPaise` is the amount in the
 * smallest currency unit (rupees x 100).
 */
export async function createRazorpayOrder(options: {
  amountPaise: number;
  currency: string;
  receipt: string;
}) {
  const order = await razorpayFetch<RazorpayOrder>("POST", "/orders", {
    amount: options.amountPaise,
    currency: options.currency,
    receipt: options.receipt,
    payment_capture: 1,
  });
  return {
    id: order.id,
    amountPaise: order.amount,
    currency: order.currency,
  };
}

export interface RazorpayPayment {
  id: string;
  order_id: string;
  amount: number;
  currency: string;
  status: string;
  entity: string;
}

export interface RazorpaySubscription {
  id: string;
  plan_id: string;
  status: string;
  quantity: number;
  total_count: number;
  current_count: number;
  notes?: Record<string, string> | null;
  created_at?: number;
  ended_at?: number | null;
}

/** Creates a recurring Razorpay subscription linked to a Razorpay plan. */
export async function createRazorpaySubscription(options: {
  planId: string;
  email: string;
  name: string;
  totalCount?: number;
  notes?: Record<string, string>;
}): Promise<RazorpaySubscription> {
  return razorpayFetch<RazorpaySubscription>("POST", "/subscriptions", {
    plan_id: options.planId,
    total_count: options.totalCount ?? 12,
    quantity: 1,
    customer_notify: 1,
    notify_email: options.email,
    notes: options.notes ?? {},
  });
}

/** Fetches a subscription by id to read its current status. */
export async function fetchRazorpaySubscription(
  subscriptionId: string,
): Promise<RazorpaySubscription> {
  return razorpayFetch<RazorpaySubscription>(
    "GET",
    `/subscriptions/${subscriptionId}`,
  );
}

/** Cancels a subscription so no further payments are collected. */
export async function cancelRazorpaySubscription(
  subscriptionId: string,
): Promise<RazorpaySubscription> {
  return razorpayFetch<RazorpaySubscription>(
    "POST",
    `/subscriptions/${subscriptionId}/cancel`,
  );
}

/**
 * Verifies a checkout signature: an HMAC-SHA256 of `orderId|paymentId`
 * signed with the API key secret. This proves the payment fields were
 * generated by Razorpay for our order.
 */
export function verifyRazorpaySignature(options: {
  orderId: string;
  paymentId: string;
  signature: string;
}): boolean {
  const config = razorpayConfig();
  if (!config) return false;

  const expected = createHmac("sha256", config.keySecret)
    .update(`${options.orderId}|${options.paymentId}`)
    .digest("hex");

  const expectedBuf = Buffer.from(expected, "hex");
  const providedBuf = Buffer.from(options.signature ?? "", "hex");
  if (
    expectedBuf.length !== providedBuf.length ||
    expectedBuf.length === 0
  ) {
    return false;
  }
  return timingSafeEqual(expectedBuf, providedBuf);
}

/**
 * Verifies the signature Razorpay returns in the checkout modal for the first
 * subscription payment: an HMAC-SHA256 of `subscriptionId|paymentId` signed
 * with the API key secret.
 */
export function verifyRazorpaySubscriptionSignature(options: {
  subscriptionId: string;
  paymentId: string;
  signature: string;
}): boolean {
  const config = razorpayConfig();
  if (!config) return false;

  const expected = createHmac("sha256", config.keySecret)
    .update(`${options.subscriptionId}|${options.paymentId}`)
    .digest("hex");

  const expectedBuf = Buffer.from(expected, "hex");
  const providedBuf = Buffer.from(options.signature ?? "", "hex");
  if (
    expectedBuf.length !== providedBuf.length ||
    expectedBuf.length === 0
  ) {
    return false;
  }
  return timingSafeEqual(expectedBuf, providedBuf);
}

/**
 * Verifies a Razorpay webhook signature (HMAC-SHA256 of the raw body signed
 * with the configured webhook secret).
 */
export function verifyRazorpayWebhookSignature(
  rawBody: string,
  signature?: string | null,
): boolean {
  const secret = process.env.RAZORPAY_WEBHOOK_SECRET;
  if (!secret || !signature) return false;

  const expected = createHmac("sha256", secret)
    .update(rawBody)
    .digest("hex");

  const expectedBuf = Buffer.from(expected, "hex");
  const providedBuf = Buffer.from(signature, "hex");
  if (
    expectedBuf.length !== providedBuf.length ||
    expectedBuf.length === 0
  ) {
    return false;
  }
  return timingSafeEqual(expectedBuf, providedBuf);
}